// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.6
// source: AuthUserAdminService/authuseradmin.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthUserAdminService_RegisterUser_FullMethodName            = "/authuseradmin.AuthUserAdminService/RegisterUser"
	AuthUserAdminService_LoginUser_FullMethodName               = "/authuseradmin.AuthUserAdminService/LoginUser"
	AuthUserAdminService_LoginWithGoogle_FullMethodName         = "/authuseradmin.AuthUserAdminService/LoginWithGoogle"
	AuthUserAdminService_TokenRefresh_FullMethodName            = "/authuseradmin.AuthUserAdminService/TokenRefresh"
	AuthUserAdminService_LogoutUser_FullMethodName              = "/authuseradmin.AuthUserAdminService/LogoutUser"
	AuthUserAdminService_ResendEmailVerification_FullMethodName = "/authuseradmin.AuthUserAdminService/ResendEmailVerification"
	AuthUserAdminService_VerifyUser_FullMethodName              = "/authuseradmin.AuthUserAdminService/VerifyUser"
	AuthUserAdminService_ForgotPassword_FullMethodName          = "/authuseradmin.AuthUserAdminService/ForgotPassword"
	AuthUserAdminService_FinishForgotPassword_FullMethodName    = "/authuseradmin.AuthUserAdminService/FinishForgotPassword"
	AuthUserAdminService_ChangePassword_FullMethodName          = "/authuseradmin.AuthUserAdminService/ChangePassword"
	AuthUserAdminService_SetUpTwoFactorAuth_FullMethodName      = "/authuseradmin.AuthUserAdminService/SetUpTwoFactorAuth"
	AuthUserAdminService_VerifyTwoFactorAuth_FullMethodName     = "/authuseradmin.AuthUserAdminService/VerifyTwoFactorAuth"
	AuthUserAdminService_DisableTwoFactorAuth_FullMethodName    = "/authuseradmin.AuthUserAdminService/DisableTwoFactorAuth"
	AuthUserAdminService_GetTwoFactorAuthStatus_FullMethodName  = "/authuseradmin.AuthUserAdminService/GetTwoFactorAuthStatus"
	AuthUserAdminService_LoginAdmin_FullMethodName              = "/authuseradmin.AuthUserAdminService/LoginAdmin"
	AuthUserAdminService_UpdateProfile_FullMethodName           = "/authuseradmin.AuthUserAdminService/UpdateProfile"
	AuthUserAdminService_UpdateProfileImage_FullMethodName      = "/authuseradmin.AuthUserAdminService/UpdateProfileImage"
	AuthUserAdminService_GetUserProfile_FullMethodName          = "/authuseradmin.AuthUserAdminService/GetUserProfile"
	AuthUserAdminService_CheckBanStatus_FullMethodName          = "/authuseradmin.AuthUserAdminService/CheckBanStatus"
	AuthUserAdminService_BanHistory_FullMethodName              = "/authuseradmin.AuthUserAdminService/BanHistory"
	AuthUserAdminService_UsernameAvailable_FullMethodName       = "/authuseradmin.AuthUserAdminService/UsernameAvailable"
	AuthUserAdminService_SearchUsers_FullMethodName             = "/authuseradmin.AuthUserAdminService/SearchUsers"
	AuthUserAdminService_FollowUser_FullMethodName              = "/authuseradmin.AuthUserAdminService/FollowUser"
	AuthUserAdminService_UnfollowUser_FullMethodName            = "/authuseradmin.AuthUserAdminService/UnfollowUser"
	AuthUserAdminService_GetFollowing_FullMethodName            = "/authuseradmin.AuthUserAdminService/GetFollowing"
	AuthUserAdminService_GetFollowers_FullMethodName            = "/authuseradmin.AuthUserAdminService/GetFollowers"
	AuthUserAdminService_GetFollowFollowingCheck_FullMethodName = "/authuseradmin.AuthUserAdminService/GetFollowFollowingCheck"
	AuthUserAdminService_AdminLogin_FullMethodName              = "/authuseradmin.AuthUserAdminService/AdminLogin"
	AuthUserAdminService_AdminProfile_FullMethodName            = "/authuseradmin.AuthUserAdminService/AdminProfile"
	AuthUserAdminService_CreateUserAdmin_FullMethodName         = "/authuseradmin.AuthUserAdminService/CreateUserAdmin"
	AuthUserAdminService_UpdateUserAdmin_FullMethodName         = "/authuseradmin.AuthUserAdminService/UpdateUserAdmin"
	AuthUserAdminService_BanUser_FullMethodName                 = "/authuseradmin.AuthUserAdminService/BanUser"
	AuthUserAdminService_UnbanUser_FullMethodName               = "/authuseradmin.AuthUserAdminService/UnbanUser"
	AuthUserAdminService_VerifyAdminUser_FullMethodName         = "/authuseradmin.AuthUserAdminService/VerifyAdminUser"
	AuthUserAdminService_UnverifyUser_FullMethodName            = "/authuseradmin.AuthUserAdminService/UnverifyUser"
	AuthUserAdminService_SoftDeleteUserAdmin_FullMethodName     = "/authuseradmin.AuthUserAdminService/SoftDeleteUserAdmin"
	AuthUserAdminService_GetAllUsers_FullMethodName             = "/authuseradmin.AuthUserAdminService/GetAllUsers"
	AuthUserAdminService_GetBulkUserMetadata_FullMethodName     = "/authuseradmin.AuthUserAdminService/GetBulkUserMetadata"
)

// AuthUserAdminServiceClient is the client API for AuthUserAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthUserAdminServiceClient interface {
	// Authentication and Security
	RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error)
	LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error)
	LoginWithGoogle(ctx context.Context, in *GoogleLoginRequest, opts ...grpc.CallOption) (*LoginUserResponse, error)
	TokenRefresh(ctx context.Context, in *TokenRefreshRequest, opts ...grpc.CallOption) (*TokenRefreshResponse, error)
	LogoutUser(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
	ResendEmailVerification(ctx context.Context, in *ResendEmailVerificationRequest, opts ...grpc.CallOption) (*ResendEmailVerificationResponse, error)
	VerifyUser(ctx context.Context, in *VerifyUserRequest, opts ...grpc.CallOption) (*VerifyUserResponse, error)
	ForgotPassword(ctx context.Context, in *ForgotPasswordRequest, opts ...grpc.CallOption) (*ForgotPasswordResponse, error)
	FinishForgotPassword(ctx context.Context, in *FinishForgotPasswordRequest, opts ...grpc.CallOption) (*FinishForgotPasswordResponse, error)
	ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordResponse, error)
	SetUpTwoFactorAuth(ctx context.Context, in *SetUpTwoFactorAuthRequest, opts ...grpc.CallOption) (*SetUpTwoFactorAuthResponse, error)
	VerifyTwoFactorAuth(ctx context.Context, in *VerifyTwoFactorAuthRequest, opts ...grpc.CallOption) (*VerifyTwoFactorAuthResponse, error)
	DisableTwoFactorAuth(ctx context.Context, in *DisableTwoFactorAuthRequest, opts ...grpc.CallOption) (*DisableTwoFactorAuthResponse, error)
	GetTwoFactorAuthStatus(ctx context.Context, in *GetTwoFactorAuthStatusRequest, opts ...grpc.CallOption) (*GetTwoFactorAuthStatusResponse, error)
	// Authentication Admin
	LoginAdmin(ctx context.Context, in *LoginAdminRequest, opts ...grpc.CallOption) (*LoginAdminResponse, error)
	// User Management
	UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*UpdateProfileResponse, error)
	UpdateProfileImage(ctx context.Context, in *UpdateProfileImageRequest, opts ...grpc.CallOption) (*UpdateProfileImageResponse, error)
	GetUserProfile(ctx context.Context, in *GetUserProfileRequest, opts ...grpc.CallOption) (*GetUserProfileResponse, error)
	CheckBanStatus(ctx context.Context, in *CheckBanStatusRequest, opts ...grpc.CallOption) (*CheckBanStatusResponse, error)
	BanHistory(ctx context.Context, in *BanHistoryRequest, opts ...grpc.CallOption) (*BanHistoryResponse, error)
	UsernameAvailable(ctx context.Context, in *UsernameAvailableRequest, opts ...grpc.CallOption) (*UsernameAvailableResponse, error)
	// Social Features
	SearchUsers(ctx context.Context, in *SearchUsersRequest, opts ...grpc.CallOption) (*SearchUsersResponse, error)
	FollowUser(ctx context.Context, in *FollowUserRequest, opts ...grpc.CallOption) (*FollowUserResponse, error)
	UnfollowUser(ctx context.Context, in *UnfollowUserRequest, opts ...grpc.CallOption) (*UnfollowUserResponse, error)
	GetFollowing(ctx context.Context, in *GetFollowingRequest, opts ...grpc.CallOption) (*GetFollowingResponse, error)
	GetFollowers(ctx context.Context, in *GetFollowersRequest, opts ...grpc.CallOption) (*GetFollowersResponse, error)
	GetFollowFollowingCheck(ctx context.Context, in *GetFollowFollowingCheckRequest, opts ...grpc.CallOption) (*GetFollowFollowingCheckResponse, error)
	// Admin Operations
	AdminLogin(ctx context.Context, in *AdminLoginRequest, opts ...grpc.CallOption) (*AdminLoginResponse, error)
	AdminProfile(ctx context.Context, in *AdminProfileRequest, opts ...grpc.CallOption) (*AdminProfileResponse, error)
	CreateUserAdmin(ctx context.Context, in *CreateUserAdminRequest, opts ...grpc.CallOption) (*CreateUserAdminResponse, error)
	UpdateUserAdmin(ctx context.Context, in *UpdateUserAdminRequest, opts ...grpc.CallOption) (*UpdateUserAdminResponse, error)
	BanUser(ctx context.Context, in *BanUserRequest, opts ...grpc.CallOption) (*BanUserResponse, error)
	UnbanUser(ctx context.Context, in *UnbanUserRequest, opts ...grpc.CallOption) (*UnbanUserResponse, error)
	VerifyAdminUser(ctx context.Context, in *VerifyAdminUserRequest, opts ...grpc.CallOption) (*VerifyAdminUserResponse, error)
	UnverifyUser(ctx context.Context, in *UnverifyUserAdminRequest, opts ...grpc.CallOption) (*UnverifyUserAdminResponse, error)
	SoftDeleteUserAdmin(ctx context.Context, in *SoftDeleteUserAdminRequest, opts ...grpc.CallOption) (*SoftDeleteUserAdminResponse, error)
	GetAllUsers(ctx context.Context, in *GetAllUsersRequest, opts ...grpc.CallOption) (*GetAllUsersResponse, error)
	// bulk
	GetBulkUserMetadata(ctx context.Context, in *GetBulkUserMetadataRequest, opts ...grpc.CallOption) (*GetBulkUserMetadataResponse, error)
}

type authUserAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthUserAdminServiceClient(cc grpc.ClientConnInterface) AuthUserAdminServiceClient {
	return &authUserAdminServiceClient{cc}
}

func (c *authUserAdminServiceClient) RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterUserResponse)
	err := c.cc.Invoke(ctx, AuthUserAdminService_RegisterUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authUserAdminServiceClient) LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginUserResponse)
	err := c.cc.Invoke(ctx, AuthUserAdminService_LoginUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authUserAdminServiceClient) LoginWithGoogle(ctx context.Context, in *GoogleLoginRequest, opts ...grpc.CallOption) (*LoginUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginUserResponse)
	err := c.cc.Invoke(ctx, AuthUserAdminService_LoginWithGoogle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authUserAdminServiceClient) TokenRefresh(ctx context.Context, in *TokenRefreshRequest, opts ...grpc.CallOption) (*TokenRefreshResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TokenRefreshResponse)
	err := c.cc.Invoke(ctx, AuthUserAdminService_TokenRefresh_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authUserAdminServiceClient) LogoutUser(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogoutResponse)
	err := c.cc.Invoke(ctx, AuthUserAdminService_LogoutUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authUserAdminServiceClient) ResendEmailVerification(ctx context.Context, in *ResendEmailVerificationRequest, opts ...grpc.CallOption) (*ResendEmailVerificationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResendEmailVerificationResponse)
	err := c.cc.Invoke(ctx, AuthUserAdminService_ResendEmailVerification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authUserAdminServiceClient) VerifyUser(ctx context.Context, in *VerifyUserRequest, opts ...grpc.CallOption) (*VerifyUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyUserResponse)
	err := c.cc.Invoke(ctx, AuthUserAdminService_VerifyUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authUserAdminServiceClient) ForgotPassword(ctx context.Context, in *ForgotPasswordRequest, opts ...grpc.CallOption) (*ForgotPasswordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForgotPasswordResponse)
	err := c.cc.Invoke(ctx, AuthUserAdminService_ForgotPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authUserAdminServiceClient) FinishForgotPassword(ctx context.Context, in *FinishForgotPasswordRequest, opts ...grpc.CallOption) (*FinishForgotPasswordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FinishForgotPasswordResponse)
	err := c.cc.Invoke(ctx, AuthUserAdminService_FinishForgotPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authUserAdminServiceClient) ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangePasswordResponse)
	err := c.cc.Invoke(ctx, AuthUserAdminService_ChangePassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authUserAdminServiceClient) SetUpTwoFactorAuth(ctx context.Context, in *SetUpTwoFactorAuthRequest, opts ...grpc.CallOption) (*SetUpTwoFactorAuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetUpTwoFactorAuthResponse)
	err := c.cc.Invoke(ctx, AuthUserAdminService_SetUpTwoFactorAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authUserAdminServiceClient) VerifyTwoFactorAuth(ctx context.Context, in *VerifyTwoFactorAuthRequest, opts ...grpc.CallOption) (*VerifyTwoFactorAuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyTwoFactorAuthResponse)
	err := c.cc.Invoke(ctx, AuthUserAdminService_VerifyTwoFactorAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authUserAdminServiceClient) DisableTwoFactorAuth(ctx context.Context, in *DisableTwoFactorAuthRequest, opts ...grpc.CallOption) (*DisableTwoFactorAuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisableTwoFactorAuthResponse)
	err := c.cc.Invoke(ctx, AuthUserAdminService_DisableTwoFactorAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authUserAdminServiceClient) GetTwoFactorAuthStatus(ctx context.Context, in *GetTwoFactorAuthStatusRequest, opts ...grpc.CallOption) (*GetTwoFactorAuthStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTwoFactorAuthStatusResponse)
	err := c.cc.Invoke(ctx, AuthUserAdminService_GetTwoFactorAuthStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authUserAdminServiceClient) LoginAdmin(ctx context.Context, in *LoginAdminRequest, opts ...grpc.CallOption) (*LoginAdminResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginAdminResponse)
	err := c.cc.Invoke(ctx, AuthUserAdminService_LoginAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authUserAdminServiceClient) UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*UpdateProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProfileResponse)
	err := c.cc.Invoke(ctx, AuthUserAdminService_UpdateProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authUserAdminServiceClient) UpdateProfileImage(ctx context.Context, in *UpdateProfileImageRequest, opts ...grpc.CallOption) (*UpdateProfileImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProfileImageResponse)
	err := c.cc.Invoke(ctx, AuthUserAdminService_UpdateProfileImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authUserAdminServiceClient) GetUserProfile(ctx context.Context, in *GetUserProfileRequest, opts ...grpc.CallOption) (*GetUserProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserProfileResponse)
	err := c.cc.Invoke(ctx, AuthUserAdminService_GetUserProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authUserAdminServiceClient) CheckBanStatus(ctx context.Context, in *CheckBanStatusRequest, opts ...grpc.CallOption) (*CheckBanStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckBanStatusResponse)
	err := c.cc.Invoke(ctx, AuthUserAdminService_CheckBanStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authUserAdminServiceClient) BanHistory(ctx context.Context, in *BanHistoryRequest, opts ...grpc.CallOption) (*BanHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BanHistoryResponse)
	err := c.cc.Invoke(ctx, AuthUserAdminService_BanHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authUserAdminServiceClient) UsernameAvailable(ctx context.Context, in *UsernameAvailableRequest, opts ...grpc.CallOption) (*UsernameAvailableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UsernameAvailableResponse)
	err := c.cc.Invoke(ctx, AuthUserAdminService_UsernameAvailable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authUserAdminServiceClient) SearchUsers(ctx context.Context, in *SearchUsersRequest, opts ...grpc.CallOption) (*SearchUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchUsersResponse)
	err := c.cc.Invoke(ctx, AuthUserAdminService_SearchUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authUserAdminServiceClient) FollowUser(ctx context.Context, in *FollowUserRequest, opts ...grpc.CallOption) (*FollowUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FollowUserResponse)
	err := c.cc.Invoke(ctx, AuthUserAdminService_FollowUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authUserAdminServiceClient) UnfollowUser(ctx context.Context, in *UnfollowUserRequest, opts ...grpc.CallOption) (*UnfollowUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnfollowUserResponse)
	err := c.cc.Invoke(ctx, AuthUserAdminService_UnfollowUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authUserAdminServiceClient) GetFollowing(ctx context.Context, in *GetFollowingRequest, opts ...grpc.CallOption) (*GetFollowingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFollowingResponse)
	err := c.cc.Invoke(ctx, AuthUserAdminService_GetFollowing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authUserAdminServiceClient) GetFollowers(ctx context.Context, in *GetFollowersRequest, opts ...grpc.CallOption) (*GetFollowersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFollowersResponse)
	err := c.cc.Invoke(ctx, AuthUserAdminService_GetFollowers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authUserAdminServiceClient) GetFollowFollowingCheck(ctx context.Context, in *GetFollowFollowingCheckRequest, opts ...grpc.CallOption) (*GetFollowFollowingCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFollowFollowingCheckResponse)
	err := c.cc.Invoke(ctx, AuthUserAdminService_GetFollowFollowingCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authUserAdminServiceClient) AdminLogin(ctx context.Context, in *AdminLoginRequest, opts ...grpc.CallOption) (*AdminLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminLoginResponse)
	err := c.cc.Invoke(ctx, AuthUserAdminService_AdminLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authUserAdminServiceClient) AdminProfile(ctx context.Context, in *AdminProfileRequest, opts ...grpc.CallOption) (*AdminProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminProfileResponse)
	err := c.cc.Invoke(ctx, AuthUserAdminService_AdminProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authUserAdminServiceClient) CreateUserAdmin(ctx context.Context, in *CreateUserAdminRequest, opts ...grpc.CallOption) (*CreateUserAdminResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUserAdminResponse)
	err := c.cc.Invoke(ctx, AuthUserAdminService_CreateUserAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authUserAdminServiceClient) UpdateUserAdmin(ctx context.Context, in *UpdateUserAdminRequest, opts ...grpc.CallOption) (*UpdateUserAdminResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserAdminResponse)
	err := c.cc.Invoke(ctx, AuthUserAdminService_UpdateUserAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authUserAdminServiceClient) BanUser(ctx context.Context, in *BanUserRequest, opts ...grpc.CallOption) (*BanUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BanUserResponse)
	err := c.cc.Invoke(ctx, AuthUserAdminService_BanUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authUserAdminServiceClient) UnbanUser(ctx context.Context, in *UnbanUserRequest, opts ...grpc.CallOption) (*UnbanUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnbanUserResponse)
	err := c.cc.Invoke(ctx, AuthUserAdminService_UnbanUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authUserAdminServiceClient) VerifyAdminUser(ctx context.Context, in *VerifyAdminUserRequest, opts ...grpc.CallOption) (*VerifyAdminUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyAdminUserResponse)
	err := c.cc.Invoke(ctx, AuthUserAdminService_VerifyAdminUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authUserAdminServiceClient) UnverifyUser(ctx context.Context, in *UnverifyUserAdminRequest, opts ...grpc.CallOption) (*UnverifyUserAdminResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnverifyUserAdminResponse)
	err := c.cc.Invoke(ctx, AuthUserAdminService_UnverifyUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authUserAdminServiceClient) SoftDeleteUserAdmin(ctx context.Context, in *SoftDeleteUserAdminRequest, opts ...grpc.CallOption) (*SoftDeleteUserAdminResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SoftDeleteUserAdminResponse)
	err := c.cc.Invoke(ctx, AuthUserAdminService_SoftDeleteUserAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authUserAdminServiceClient) GetAllUsers(ctx context.Context, in *GetAllUsersRequest, opts ...grpc.CallOption) (*GetAllUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllUsersResponse)
	err := c.cc.Invoke(ctx, AuthUserAdminService_GetAllUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authUserAdminServiceClient) GetBulkUserMetadata(ctx context.Context, in *GetBulkUserMetadataRequest, opts ...grpc.CallOption) (*GetBulkUserMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBulkUserMetadataResponse)
	err := c.cc.Invoke(ctx, AuthUserAdminService_GetBulkUserMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthUserAdminServiceServer is the server API for AuthUserAdminService service.
// All implementations must embed UnimplementedAuthUserAdminServiceServer
// for forward compatibility.
type AuthUserAdminServiceServer interface {
	// Authentication and Security
	RegisterUser(context.Context, *RegisterUserRequest) (*RegisterUserResponse, error)
	LoginUser(context.Context, *LoginUserRequest) (*LoginUserResponse, error)
	LoginWithGoogle(context.Context, *GoogleLoginRequest) (*LoginUserResponse, error)
	TokenRefresh(context.Context, *TokenRefreshRequest) (*TokenRefreshResponse, error)
	LogoutUser(context.Context, *LogoutRequest) (*LogoutResponse, error)
	ResendEmailVerification(context.Context, *ResendEmailVerificationRequest) (*ResendEmailVerificationResponse, error)
	VerifyUser(context.Context, *VerifyUserRequest) (*VerifyUserResponse, error)
	ForgotPassword(context.Context, *ForgotPasswordRequest) (*ForgotPasswordResponse, error)
	FinishForgotPassword(context.Context, *FinishForgotPasswordRequest) (*FinishForgotPasswordResponse, error)
	ChangePassword(context.Context, *ChangePasswordRequest) (*ChangePasswordResponse, error)
	SetUpTwoFactorAuth(context.Context, *SetUpTwoFactorAuthRequest) (*SetUpTwoFactorAuthResponse, error)
	VerifyTwoFactorAuth(context.Context, *VerifyTwoFactorAuthRequest) (*VerifyTwoFactorAuthResponse, error)
	DisableTwoFactorAuth(context.Context, *DisableTwoFactorAuthRequest) (*DisableTwoFactorAuthResponse, error)
	GetTwoFactorAuthStatus(context.Context, *GetTwoFactorAuthStatusRequest) (*GetTwoFactorAuthStatusResponse, error)
	// Authentication Admin
	LoginAdmin(context.Context, *LoginAdminRequest) (*LoginAdminResponse, error)
	// User Management
	UpdateProfile(context.Context, *UpdateProfileRequest) (*UpdateProfileResponse, error)
	UpdateProfileImage(context.Context, *UpdateProfileImageRequest) (*UpdateProfileImageResponse, error)
	GetUserProfile(context.Context, *GetUserProfileRequest) (*GetUserProfileResponse, error)
	CheckBanStatus(context.Context, *CheckBanStatusRequest) (*CheckBanStatusResponse, error)
	BanHistory(context.Context, *BanHistoryRequest) (*BanHistoryResponse, error)
	UsernameAvailable(context.Context, *UsernameAvailableRequest) (*UsernameAvailableResponse, error)
	// Social Features
	SearchUsers(context.Context, *SearchUsersRequest) (*SearchUsersResponse, error)
	FollowUser(context.Context, *FollowUserRequest) (*FollowUserResponse, error)
	UnfollowUser(context.Context, *UnfollowUserRequest) (*UnfollowUserResponse, error)
	GetFollowing(context.Context, *GetFollowingRequest) (*GetFollowingResponse, error)
	GetFollowers(context.Context, *GetFollowersRequest) (*GetFollowersResponse, error)
	GetFollowFollowingCheck(context.Context, *GetFollowFollowingCheckRequest) (*GetFollowFollowingCheckResponse, error)
	// Admin Operations
	AdminLogin(context.Context, *AdminLoginRequest) (*AdminLoginResponse, error)
	AdminProfile(context.Context, *AdminProfileRequest) (*AdminProfileResponse, error)
	CreateUserAdmin(context.Context, *CreateUserAdminRequest) (*CreateUserAdminResponse, error)
	UpdateUserAdmin(context.Context, *UpdateUserAdminRequest) (*UpdateUserAdminResponse, error)
	BanUser(context.Context, *BanUserRequest) (*BanUserResponse, error)
	UnbanUser(context.Context, *UnbanUserRequest) (*UnbanUserResponse, error)
	VerifyAdminUser(context.Context, *VerifyAdminUserRequest) (*VerifyAdminUserResponse, error)
	UnverifyUser(context.Context, *UnverifyUserAdminRequest) (*UnverifyUserAdminResponse, error)
	SoftDeleteUserAdmin(context.Context, *SoftDeleteUserAdminRequest) (*SoftDeleteUserAdminResponse, error)
	GetAllUsers(context.Context, *GetAllUsersRequest) (*GetAllUsersResponse, error)
	// bulk
	GetBulkUserMetadata(context.Context, *GetBulkUserMetadataRequest) (*GetBulkUserMetadataResponse, error)
	mustEmbedUnimplementedAuthUserAdminServiceServer()
}

// UnimplementedAuthUserAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthUserAdminServiceServer struct{}

func (UnimplementedAuthUserAdminServiceServer) RegisterUser(context.Context, *RegisterUserRequest) (*RegisterUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterUser not implemented")
}
func (UnimplementedAuthUserAdminServiceServer) LoginUser(context.Context, *LoginUserRequest) (*LoginUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginUser not implemented")
}
func (UnimplementedAuthUserAdminServiceServer) LoginWithGoogle(context.Context, *GoogleLoginRequest) (*LoginUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginWithGoogle not implemented")
}
func (UnimplementedAuthUserAdminServiceServer) TokenRefresh(context.Context, *TokenRefreshRequest) (*TokenRefreshResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TokenRefresh not implemented")
}
func (UnimplementedAuthUserAdminServiceServer) LogoutUser(context.Context, *LogoutRequest) (*LogoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LogoutUser not implemented")
}
func (UnimplementedAuthUserAdminServiceServer) ResendEmailVerification(context.Context, *ResendEmailVerificationRequest) (*ResendEmailVerificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResendEmailVerification not implemented")
}
func (UnimplementedAuthUserAdminServiceServer) VerifyUser(context.Context, *VerifyUserRequest) (*VerifyUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyUser not implemented")
}
func (UnimplementedAuthUserAdminServiceServer) ForgotPassword(context.Context, *ForgotPasswordRequest) (*ForgotPasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForgotPassword not implemented")
}
func (UnimplementedAuthUserAdminServiceServer) FinishForgotPassword(context.Context, *FinishForgotPasswordRequest) (*FinishForgotPasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinishForgotPassword not implemented")
}
func (UnimplementedAuthUserAdminServiceServer) ChangePassword(context.Context, *ChangePasswordRequest) (*ChangePasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangePassword not implemented")
}
func (UnimplementedAuthUserAdminServiceServer) SetUpTwoFactorAuth(context.Context, *SetUpTwoFactorAuthRequest) (*SetUpTwoFactorAuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetUpTwoFactorAuth not implemented")
}
func (UnimplementedAuthUserAdminServiceServer) VerifyTwoFactorAuth(context.Context, *VerifyTwoFactorAuthRequest) (*VerifyTwoFactorAuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyTwoFactorAuth not implemented")
}
func (UnimplementedAuthUserAdminServiceServer) DisableTwoFactorAuth(context.Context, *DisableTwoFactorAuthRequest) (*DisableTwoFactorAuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisableTwoFactorAuth not implemented")
}
func (UnimplementedAuthUserAdminServiceServer) GetTwoFactorAuthStatus(context.Context, *GetTwoFactorAuthStatusRequest) (*GetTwoFactorAuthStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTwoFactorAuthStatus not implemented")
}
func (UnimplementedAuthUserAdminServiceServer) LoginAdmin(context.Context, *LoginAdminRequest) (*LoginAdminResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginAdmin not implemented")
}
func (UnimplementedAuthUserAdminServiceServer) UpdateProfile(context.Context, *UpdateProfileRequest) (*UpdateProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProfile not implemented")
}
func (UnimplementedAuthUserAdminServiceServer) UpdateProfileImage(context.Context, *UpdateProfileImageRequest) (*UpdateProfileImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProfileImage not implemented")
}
func (UnimplementedAuthUserAdminServiceServer) GetUserProfile(context.Context, *GetUserProfileRequest) (*GetUserProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserProfile not implemented")
}
func (UnimplementedAuthUserAdminServiceServer) CheckBanStatus(context.Context, *CheckBanStatusRequest) (*CheckBanStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckBanStatus not implemented")
}
func (UnimplementedAuthUserAdminServiceServer) BanHistory(context.Context, *BanHistoryRequest) (*BanHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BanHistory not implemented")
}
func (UnimplementedAuthUserAdminServiceServer) UsernameAvailable(context.Context, *UsernameAvailableRequest) (*UsernameAvailableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UsernameAvailable not implemented")
}
func (UnimplementedAuthUserAdminServiceServer) SearchUsers(context.Context, *SearchUsersRequest) (*SearchUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchUsers not implemented")
}
func (UnimplementedAuthUserAdminServiceServer) FollowUser(context.Context, *FollowUserRequest) (*FollowUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FollowUser not implemented")
}
func (UnimplementedAuthUserAdminServiceServer) UnfollowUser(context.Context, *UnfollowUserRequest) (*UnfollowUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnfollowUser not implemented")
}
func (UnimplementedAuthUserAdminServiceServer) GetFollowing(context.Context, *GetFollowingRequest) (*GetFollowingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFollowing not implemented")
}
func (UnimplementedAuthUserAdminServiceServer) GetFollowers(context.Context, *GetFollowersRequest) (*GetFollowersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFollowers not implemented")
}
func (UnimplementedAuthUserAdminServiceServer) GetFollowFollowingCheck(context.Context, *GetFollowFollowingCheckRequest) (*GetFollowFollowingCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFollowFollowingCheck not implemented")
}
func (UnimplementedAuthUserAdminServiceServer) AdminLogin(context.Context, *AdminLoginRequest) (*AdminLoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminLogin not implemented")
}
func (UnimplementedAuthUserAdminServiceServer) AdminProfile(context.Context, *AdminProfileRequest) (*AdminProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminProfile not implemented")
}
func (UnimplementedAuthUserAdminServiceServer) CreateUserAdmin(context.Context, *CreateUserAdminRequest) (*CreateUserAdminResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUserAdmin not implemented")
}
func (UnimplementedAuthUserAdminServiceServer) UpdateUserAdmin(context.Context, *UpdateUserAdminRequest) (*UpdateUserAdminResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserAdmin not implemented")
}
func (UnimplementedAuthUserAdminServiceServer) BanUser(context.Context, *BanUserRequest) (*BanUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BanUser not implemented")
}
func (UnimplementedAuthUserAdminServiceServer) UnbanUser(context.Context, *UnbanUserRequest) (*UnbanUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnbanUser not implemented")
}
func (UnimplementedAuthUserAdminServiceServer) VerifyAdminUser(context.Context, *VerifyAdminUserRequest) (*VerifyAdminUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyAdminUser not implemented")
}
func (UnimplementedAuthUserAdminServiceServer) UnverifyUser(context.Context, *UnverifyUserAdminRequest) (*UnverifyUserAdminResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnverifyUser not implemented")
}
func (UnimplementedAuthUserAdminServiceServer) SoftDeleteUserAdmin(context.Context, *SoftDeleteUserAdminRequest) (*SoftDeleteUserAdminResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SoftDeleteUserAdmin not implemented")
}
func (UnimplementedAuthUserAdminServiceServer) GetAllUsers(context.Context, *GetAllUsersRequest) (*GetAllUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllUsers not implemented")
}
func (UnimplementedAuthUserAdminServiceServer) GetBulkUserMetadata(context.Context, *GetBulkUserMetadataRequest) (*GetBulkUserMetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBulkUserMetadata not implemented")
}
func (UnimplementedAuthUserAdminServiceServer) mustEmbedUnimplementedAuthUserAdminServiceServer() {}
func (UnimplementedAuthUserAdminServiceServer) testEmbeddedByValue()                              {}

// UnsafeAuthUserAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthUserAdminServiceServer will
// result in compilation errors.
type UnsafeAuthUserAdminServiceServer interface {
	mustEmbedUnimplementedAuthUserAdminServiceServer()
}

func RegisterAuthUserAdminServiceServer(s grpc.ServiceRegistrar, srv AuthUserAdminServiceServer) {
	// If the following call pancis, it indicates UnimplementedAuthUserAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthUserAdminService_ServiceDesc, srv)
}

func _AuthUserAdminService_RegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthUserAdminServiceServer).RegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthUserAdminService_RegisterUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthUserAdminServiceServer).RegisterUser(ctx, req.(*RegisterUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthUserAdminService_LoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthUserAdminServiceServer).LoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthUserAdminService_LoginUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthUserAdminServiceServer).LoginUser(ctx, req.(*LoginUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthUserAdminService_LoginWithGoogle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoogleLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthUserAdminServiceServer).LoginWithGoogle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthUserAdminService_LoginWithGoogle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthUserAdminServiceServer).LoginWithGoogle(ctx, req.(*GoogleLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthUserAdminService_TokenRefresh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenRefreshRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthUserAdminServiceServer).TokenRefresh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthUserAdminService_TokenRefresh_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthUserAdminServiceServer).TokenRefresh(ctx, req.(*TokenRefreshRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthUserAdminService_LogoutUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthUserAdminServiceServer).LogoutUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthUserAdminService_LogoutUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthUserAdminServiceServer).LogoutUser(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthUserAdminService_ResendEmailVerification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResendEmailVerificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthUserAdminServiceServer).ResendEmailVerification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthUserAdminService_ResendEmailVerification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthUserAdminServiceServer).ResendEmailVerification(ctx, req.(*ResendEmailVerificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthUserAdminService_VerifyUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthUserAdminServiceServer).VerifyUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthUserAdminService_VerifyUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthUserAdminServiceServer).VerifyUser(ctx, req.(*VerifyUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthUserAdminService_ForgotPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForgotPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthUserAdminServiceServer).ForgotPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthUserAdminService_ForgotPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthUserAdminServiceServer).ForgotPassword(ctx, req.(*ForgotPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthUserAdminService_FinishForgotPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinishForgotPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthUserAdminServiceServer).FinishForgotPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthUserAdminService_FinishForgotPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthUserAdminServiceServer).FinishForgotPassword(ctx, req.(*FinishForgotPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthUserAdminService_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthUserAdminServiceServer).ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthUserAdminService_ChangePassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthUserAdminServiceServer).ChangePassword(ctx, req.(*ChangePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthUserAdminService_SetUpTwoFactorAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUpTwoFactorAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthUserAdminServiceServer).SetUpTwoFactorAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthUserAdminService_SetUpTwoFactorAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthUserAdminServiceServer).SetUpTwoFactorAuth(ctx, req.(*SetUpTwoFactorAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthUserAdminService_VerifyTwoFactorAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyTwoFactorAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthUserAdminServiceServer).VerifyTwoFactorAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthUserAdminService_VerifyTwoFactorAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthUserAdminServiceServer).VerifyTwoFactorAuth(ctx, req.(*VerifyTwoFactorAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthUserAdminService_DisableTwoFactorAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisableTwoFactorAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthUserAdminServiceServer).DisableTwoFactorAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthUserAdminService_DisableTwoFactorAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthUserAdminServiceServer).DisableTwoFactorAuth(ctx, req.(*DisableTwoFactorAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthUserAdminService_GetTwoFactorAuthStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTwoFactorAuthStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthUserAdminServiceServer).GetTwoFactorAuthStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthUserAdminService_GetTwoFactorAuthStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthUserAdminServiceServer).GetTwoFactorAuthStatus(ctx, req.(*GetTwoFactorAuthStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthUserAdminService_LoginAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthUserAdminServiceServer).LoginAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthUserAdminService_LoginAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthUserAdminServiceServer).LoginAdmin(ctx, req.(*LoginAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthUserAdminService_UpdateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthUserAdminServiceServer).UpdateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthUserAdminService_UpdateProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthUserAdminServiceServer).UpdateProfile(ctx, req.(*UpdateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthUserAdminService_UpdateProfileImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProfileImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthUserAdminServiceServer).UpdateProfileImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthUserAdminService_UpdateProfileImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthUserAdminServiceServer).UpdateProfileImage(ctx, req.(*UpdateProfileImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthUserAdminService_GetUserProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthUserAdminServiceServer).GetUserProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthUserAdminService_GetUserProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthUserAdminServiceServer).GetUserProfile(ctx, req.(*GetUserProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthUserAdminService_CheckBanStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckBanStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthUserAdminServiceServer).CheckBanStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthUserAdminService_CheckBanStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthUserAdminServiceServer).CheckBanStatus(ctx, req.(*CheckBanStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthUserAdminService_BanHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BanHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthUserAdminServiceServer).BanHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthUserAdminService_BanHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthUserAdminServiceServer).BanHistory(ctx, req.(*BanHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthUserAdminService_UsernameAvailable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsernameAvailableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthUserAdminServiceServer).UsernameAvailable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthUserAdminService_UsernameAvailable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthUserAdminServiceServer).UsernameAvailable(ctx, req.(*UsernameAvailableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthUserAdminService_SearchUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthUserAdminServiceServer).SearchUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthUserAdminService_SearchUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthUserAdminServiceServer).SearchUsers(ctx, req.(*SearchUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthUserAdminService_FollowUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthUserAdminServiceServer).FollowUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthUserAdminService_FollowUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthUserAdminServiceServer).FollowUser(ctx, req.(*FollowUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthUserAdminService_UnfollowUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnfollowUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthUserAdminServiceServer).UnfollowUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthUserAdminService_UnfollowUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthUserAdminServiceServer).UnfollowUser(ctx, req.(*UnfollowUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthUserAdminService_GetFollowing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFollowingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthUserAdminServiceServer).GetFollowing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthUserAdminService_GetFollowing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthUserAdminServiceServer).GetFollowing(ctx, req.(*GetFollowingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthUserAdminService_GetFollowers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFollowersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthUserAdminServiceServer).GetFollowers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthUserAdminService_GetFollowers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthUserAdminServiceServer).GetFollowers(ctx, req.(*GetFollowersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthUserAdminService_GetFollowFollowingCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFollowFollowingCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthUserAdminServiceServer).GetFollowFollowingCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthUserAdminService_GetFollowFollowingCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthUserAdminServiceServer).GetFollowFollowingCheck(ctx, req.(*GetFollowFollowingCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthUserAdminService_AdminLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthUserAdminServiceServer).AdminLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthUserAdminService_AdminLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthUserAdminServiceServer).AdminLogin(ctx, req.(*AdminLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthUserAdminService_AdminProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthUserAdminServiceServer).AdminProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthUserAdminService_AdminProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthUserAdminServiceServer).AdminProfile(ctx, req.(*AdminProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthUserAdminService_CreateUserAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthUserAdminServiceServer).CreateUserAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthUserAdminService_CreateUserAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthUserAdminServiceServer).CreateUserAdmin(ctx, req.(*CreateUserAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthUserAdminService_UpdateUserAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthUserAdminServiceServer).UpdateUserAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthUserAdminService_UpdateUserAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthUserAdminServiceServer).UpdateUserAdmin(ctx, req.(*UpdateUserAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthUserAdminService_BanUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BanUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthUserAdminServiceServer).BanUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthUserAdminService_BanUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthUserAdminServiceServer).BanUser(ctx, req.(*BanUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthUserAdminService_UnbanUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnbanUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthUserAdminServiceServer).UnbanUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthUserAdminService_UnbanUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthUserAdminServiceServer).UnbanUser(ctx, req.(*UnbanUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthUserAdminService_VerifyAdminUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyAdminUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthUserAdminServiceServer).VerifyAdminUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthUserAdminService_VerifyAdminUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthUserAdminServiceServer).VerifyAdminUser(ctx, req.(*VerifyAdminUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthUserAdminService_UnverifyUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnverifyUserAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthUserAdminServiceServer).UnverifyUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthUserAdminService_UnverifyUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthUserAdminServiceServer).UnverifyUser(ctx, req.(*UnverifyUserAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthUserAdminService_SoftDeleteUserAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SoftDeleteUserAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthUserAdminServiceServer).SoftDeleteUserAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthUserAdminService_SoftDeleteUserAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthUserAdminServiceServer).SoftDeleteUserAdmin(ctx, req.(*SoftDeleteUserAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthUserAdminService_GetAllUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthUserAdminServiceServer).GetAllUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthUserAdminService_GetAllUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthUserAdminServiceServer).GetAllUsers(ctx, req.(*GetAllUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthUserAdminService_GetBulkUserMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBulkUserMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthUserAdminServiceServer).GetBulkUserMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthUserAdminService_GetBulkUserMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthUserAdminServiceServer).GetBulkUserMetadata(ctx, req.(*GetBulkUserMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthUserAdminService_ServiceDesc is the grpc.ServiceDesc for AuthUserAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthUserAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "authuseradmin.AuthUserAdminService",
	HandlerType: (*AuthUserAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterUser",
			Handler:    _AuthUserAdminService_RegisterUser_Handler,
		},
		{
			MethodName: "LoginUser",
			Handler:    _AuthUserAdminService_LoginUser_Handler,
		},
		{
			MethodName: "LoginWithGoogle",
			Handler:    _AuthUserAdminService_LoginWithGoogle_Handler,
		},
		{
			MethodName: "TokenRefresh",
			Handler:    _AuthUserAdminService_TokenRefresh_Handler,
		},
		{
			MethodName: "LogoutUser",
			Handler:    _AuthUserAdminService_LogoutUser_Handler,
		},
		{
			MethodName: "ResendEmailVerification",
			Handler:    _AuthUserAdminService_ResendEmailVerification_Handler,
		},
		{
			MethodName: "VerifyUser",
			Handler:    _AuthUserAdminService_VerifyUser_Handler,
		},
		{
			MethodName: "ForgotPassword",
			Handler:    _AuthUserAdminService_ForgotPassword_Handler,
		},
		{
			MethodName: "FinishForgotPassword",
			Handler:    _AuthUserAdminService_FinishForgotPassword_Handler,
		},
		{
			MethodName: "ChangePassword",
			Handler:    _AuthUserAdminService_ChangePassword_Handler,
		},
		{
			MethodName: "SetUpTwoFactorAuth",
			Handler:    _AuthUserAdminService_SetUpTwoFactorAuth_Handler,
		},
		{
			MethodName: "VerifyTwoFactorAuth",
			Handler:    _AuthUserAdminService_VerifyTwoFactorAuth_Handler,
		},
		{
			MethodName: "DisableTwoFactorAuth",
			Handler:    _AuthUserAdminService_DisableTwoFactorAuth_Handler,
		},
		{
			MethodName: "GetTwoFactorAuthStatus",
			Handler:    _AuthUserAdminService_GetTwoFactorAuthStatus_Handler,
		},
		{
			MethodName: "LoginAdmin",
			Handler:    _AuthUserAdminService_LoginAdmin_Handler,
		},
		{
			MethodName: "UpdateProfile",
			Handler:    _AuthUserAdminService_UpdateProfile_Handler,
		},
		{
			MethodName: "UpdateProfileImage",
			Handler:    _AuthUserAdminService_UpdateProfileImage_Handler,
		},
		{
			MethodName: "GetUserProfile",
			Handler:    _AuthUserAdminService_GetUserProfile_Handler,
		},
		{
			MethodName: "CheckBanStatus",
			Handler:    _AuthUserAdminService_CheckBanStatus_Handler,
		},
		{
			MethodName: "BanHistory",
			Handler:    _AuthUserAdminService_BanHistory_Handler,
		},
		{
			MethodName: "UsernameAvailable",
			Handler:    _AuthUserAdminService_UsernameAvailable_Handler,
		},
		{
			MethodName: "SearchUsers",
			Handler:    _AuthUserAdminService_SearchUsers_Handler,
		},
		{
			MethodName: "FollowUser",
			Handler:    _AuthUserAdminService_FollowUser_Handler,
		},
		{
			MethodName: "UnfollowUser",
			Handler:    _AuthUserAdminService_UnfollowUser_Handler,
		},
		{
			MethodName: "GetFollowing",
			Handler:    _AuthUserAdminService_GetFollowing_Handler,
		},
		{
			MethodName: "GetFollowers",
			Handler:    _AuthUserAdminService_GetFollowers_Handler,
		},
		{
			MethodName: "GetFollowFollowingCheck",
			Handler:    _AuthUserAdminService_GetFollowFollowingCheck_Handler,
		},
		{
			MethodName: "AdminLogin",
			Handler:    _AuthUserAdminService_AdminLogin_Handler,
		},
		{
			MethodName: "AdminProfile",
			Handler:    _AuthUserAdminService_AdminProfile_Handler,
		},
		{
			MethodName: "CreateUserAdmin",
			Handler:    _AuthUserAdminService_CreateUserAdmin_Handler,
		},
		{
			MethodName: "UpdateUserAdmin",
			Handler:    _AuthUserAdminService_UpdateUserAdmin_Handler,
		},
		{
			MethodName: "BanUser",
			Handler:    _AuthUserAdminService_BanUser_Handler,
		},
		{
			MethodName: "UnbanUser",
			Handler:    _AuthUserAdminService_UnbanUser_Handler,
		},
		{
			MethodName: "VerifyAdminUser",
			Handler:    _AuthUserAdminService_VerifyAdminUser_Handler,
		},
		{
			MethodName: "UnverifyUser",
			Handler:    _AuthUserAdminService_UnverifyUser_Handler,
		},
		{
			MethodName: "SoftDeleteUserAdmin",
			Handler:    _AuthUserAdminService_SoftDeleteUserAdmin_Handler,
		},
		{
			MethodName: "GetAllUsers",
			Handler:    _AuthUserAdminService_GetAllUsers_Handler,
		},
		{
			MethodName: "GetBulkUserMetadata",
			Handler:    _AuthUserAdminService_GetBulkUserMetadata_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "AuthUserAdminService/authuseradmin.proto",
}
