// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.6
// source: ProblemsService/problemsservice.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProblemsService_CreateProblem_FullMethodName                          = "/problems.ProblemsService/CreateProblem"
	ProblemsService_UpdateProblem_FullMethodName                          = "/problems.ProblemsService/UpdateProblem"
	ProblemsService_DeleteProblem_FullMethodName                          = "/problems.ProblemsService/DeleteProblem"
	ProblemsService_GetProblem_FullMethodName                             = "/problems.ProblemsService/GetProblem"
	ProblemsService_ListProblems_FullMethodName                           = "/problems.ProblemsService/ListProblems"
	ProblemsService_GetProblemByIdSlug_FullMethodName                     = "/problems.ProblemsService/GetProblemByIdSlug"
	ProblemsService_GetProblemMetadataList_FullMethodName                 = "/problems.ProblemsService/GetProblemMetadataList"
	ProblemsService_AddTestCases_FullMethodName                           = "/problems.ProblemsService/AddTestCases"
	ProblemsService_DeleteTestCase_FullMethodName                         = "/problems.ProblemsService/DeleteTestCase"
	ProblemsService_GetLanguageSupports_FullMethodName                    = "/problems.ProblemsService/GetLanguageSupports"
	ProblemsService_AddLanguageSupport_FullMethodName                     = "/problems.ProblemsService/AddLanguageSupport"
	ProblemsService_UpdateLanguageSupport_FullMethodName                  = "/problems.ProblemsService/UpdateLanguageSupport"
	ProblemsService_RemoveLanguageSupport_FullMethodName                  = "/problems.ProblemsService/RemoveLanguageSupport"
	ProblemsService_FullValidationByProblemId_FullMethodName              = "/problems.ProblemsService/FullValidationByProblemId"
	ProblemsService_RunUserCodeProblem_FullMethodName                     = "/problems.ProblemsService/RunUserCodeProblem"
	ProblemsService_GetSubmissionsByOptionalProblemId_FullMethodName      = "/problems.ProblemsService/GetSubmissionsByOptionalProblemId"
	ProblemsService_GetSubmissionsById_FullMethodName                     = "/problems.ProblemsService/GetSubmissionsById"
	ProblemsService_GetProblemsDoneStatistics_FullMethodName              = "/problems.ProblemsService/GetProblemsDoneStatistics"
	ProblemsService_ForceChangeUserEntityInSubmission_FullMethodName      = "/problems.ProblemsService/ForceChangeUserEntityInSubmission"
	ProblemsService_GetMonthlyActivityHeatmap_FullMethodName              = "/problems.ProblemsService/GetMonthlyActivityHeatmap"
	ProblemsService_GetTopKGlobal_FullMethodName                          = "/problems.ProblemsService/GetTopKGlobal"
	ProblemsService_GetTopKEntity_FullMethodName                          = "/problems.ProblemsService/GetTopKEntity"
	ProblemsService_GetUserRank_FullMethodName                            = "/problems.ProblemsService/GetUserRank"
	ProblemsService_GetLeaderboardData_FullMethodName                     = "/problems.ProblemsService/GetLeaderboardData"
	ProblemsService_GetBulkProblemMetadata_FullMethodName                 = "/problems.ProblemsService/GetBulkProblemMetadata"
	ProblemsService_VerifyProblemExistenceBulk_FullMethodName             = "/problems.ProblemsService/VerifyProblemExistenceBulk"
	ProblemsService_RandomProblemIdsGenWithDifficultyRatio_FullMethodName = "/problems.ProblemsService/RandomProblemIdsGenWithDifficultyRatio"
	ProblemsService_ProblemIdsDoneByUserId_FullMethodName                 = "/problems.ProblemsService/ProblemIdsDoneByUserId"
	ProblemsService_ProblemCountMetadata_FullMethodName                   = "/problems.ProblemsService/ProblemCountMetadata"
)

// ProblemsServiceClient is the client API for ProblemsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProblemsServiceClient interface {
	CreateProblem(ctx context.Context, in *CreateProblemRequest, opts ...grpc.CallOption) (*CreateProblemResponse, error)
	UpdateProblem(ctx context.Context, in *UpdateProblemRequest, opts ...grpc.CallOption) (*UpdateProblemResponse, error)
	DeleteProblem(ctx context.Context, in *DeleteProblemRequest, opts ...grpc.CallOption) (*DeleteProblemResponse, error)
	GetProblem(ctx context.Context, in *GetProblemRequest, opts ...grpc.CallOption) (*GetProblemResponse, error)
	ListProblems(ctx context.Context, in *ListProblemsRequest, opts ...grpc.CallOption) (*ListProblemsResponse, error)
	GetProblemByIdSlug(ctx context.Context, in *GetProblemByIdSlugRequest, opts ...grpc.CallOption) (*GetProblemByIdSlugResponse, error)
	GetProblemMetadataList(ctx context.Context, in *GetProblemMetadataListRequest, opts ...grpc.CallOption) (*GetProblemMetadataListResponse, error)
	AddTestCases(ctx context.Context, in *AddTestCasesRequest, opts ...grpc.CallOption) (*AddTestCasesResponse, error)
	// rpc EditTestcases(EditTestcasesRequest) returns (EditTestCasesResponse); TODO : use testcaseId for updates :priority low
	DeleteTestCase(ctx context.Context, in *DeleteTestCaseRequest, opts ...grpc.CallOption) (*DeleteTestCaseResponse, error)
	GetLanguageSupports(ctx context.Context, in *GetLanguageSupportsRequest, opts ...grpc.CallOption) (*GetLanguageSupportsResponse, error)
	AddLanguageSupport(ctx context.Context, in *AddLanguageSupportRequest, opts ...grpc.CallOption) (*AddLanguageSupportResponse, error)
	UpdateLanguageSupport(ctx context.Context, in *UpdateLanguageSupportRequest, opts ...grpc.CallOption) (*UpdateLanguageSupportResponse, error)
	RemoveLanguageSupport(ctx context.Context, in *RemoveLanguageSupportRequest, opts ...grpc.CallOption) (*RemoveLanguageSupportResponse, error)
	FullValidationByProblemId(ctx context.Context, in *FullValidationByProblemIdRequest, opts ...grpc.CallOption) (*FullValidationByProblemIdResponse, error)
	RunUserCodeProblem(ctx context.Context, in *RunProblemRequest, opts ...grpc.CallOption) (*RunProblemResponse, error)
	GetSubmissionsByOptionalProblemId(ctx context.Context, in *GetSubmissionsRequest, opts ...grpc.CallOption) (*GetSubmissionsResponse, error)
	GetSubmissionsById(ctx context.Context, in *GetSubmissionsByIdRequest, opts ...grpc.CallOption) (*GetSubmissionsByIdResponse, error)
	// Leaderboard
	GetProblemsDoneStatistics(ctx context.Context, in *GetProblemsDoneStatisticsRequest, opts ...grpc.CallOption) (*GetProblemsDoneStatisticsResponse, error)
	ForceChangeUserEntityInSubmission(ctx context.Context, in *ForceChangeUserEntityInSubmissionRequest, opts ...grpc.CallOption) (*ForceChangeUserEntityInSubmissionResponse, error)
	// Activity Contribution
	GetMonthlyActivityHeatmap(ctx context.Context, in *GetMonthlyActivityHeatmapRequest, opts ...grpc.CallOption) (*GetMonthlyActivityHeatmapResponse, error)
	// Leaderboard Methods
	GetTopKGlobal(ctx context.Context, in *GetTopKGlobalRequest, opts ...grpc.CallOption) (*GetTopKGlobalResponse, error)
	GetTopKEntity(ctx context.Context, in *GetTopKEntityRequest, opts ...grpc.CallOption) (*GetTopKEntityResponse, error)
	GetUserRank(ctx context.Context, in *GetUserRankRequest, opts ...grpc.CallOption) (*GetUserRankResponse, error)
	GetLeaderboardData(ctx context.Context, in *GetLeaderboardDataRequest, opts ...grpc.CallOption) (*GetLeaderboardDataResponse, error)
	GetBulkProblemMetadata(ctx context.Context, in *GetBulkProblemMetadataRequest, opts ...grpc.CallOption) (*GetBulkProblemMetadataResponse, error)
	VerifyProblemExistenceBulk(ctx context.Context, in *VerifyProblemExistenceBulkRequest, opts ...grpc.CallOption) (*VerifyProblemExistenceBulkResponse, error)
	RandomProblemIdsGenWithDifficultyRatio(ctx context.Context, in *RandomProblemIdsGenWithDifficultyRatioRequest, opts ...grpc.CallOption) (*RandomProblemIdsGenWithDifficultyRatioResponse, error)
	ProblemIdsDoneByUserId(ctx context.Context, in *ProblemIdsDoneByUserIdRequest, opts ...grpc.CallOption) (*ProblemIdsDoneByUserIdResponse, error)
	ProblemCountMetadata(ctx context.Context, in *ProblemCountMetadataRequest, opts ...grpc.CallOption) (*ProblemCountMetadataResponse, error)
}

type problemsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProblemsServiceClient(cc grpc.ClientConnInterface) ProblemsServiceClient {
	return &problemsServiceClient{cc}
}

func (c *problemsServiceClient) CreateProblem(ctx context.Context, in *CreateProblemRequest, opts ...grpc.CallOption) (*CreateProblemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateProblemResponse)
	err := c.cc.Invoke(ctx, ProblemsService_CreateProblem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemsServiceClient) UpdateProblem(ctx context.Context, in *UpdateProblemRequest, opts ...grpc.CallOption) (*UpdateProblemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProblemResponse)
	err := c.cc.Invoke(ctx, ProblemsService_UpdateProblem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemsServiceClient) DeleteProblem(ctx context.Context, in *DeleteProblemRequest, opts ...grpc.CallOption) (*DeleteProblemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteProblemResponse)
	err := c.cc.Invoke(ctx, ProblemsService_DeleteProblem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemsServiceClient) GetProblem(ctx context.Context, in *GetProblemRequest, opts ...grpc.CallOption) (*GetProblemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProblemResponse)
	err := c.cc.Invoke(ctx, ProblemsService_GetProblem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemsServiceClient) ListProblems(ctx context.Context, in *ListProblemsRequest, opts ...grpc.CallOption) (*ListProblemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProblemsResponse)
	err := c.cc.Invoke(ctx, ProblemsService_ListProblems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemsServiceClient) GetProblemByIdSlug(ctx context.Context, in *GetProblemByIdSlugRequest, opts ...grpc.CallOption) (*GetProblemByIdSlugResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProblemByIdSlugResponse)
	err := c.cc.Invoke(ctx, ProblemsService_GetProblemByIdSlug_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemsServiceClient) GetProblemMetadataList(ctx context.Context, in *GetProblemMetadataListRequest, opts ...grpc.CallOption) (*GetProblemMetadataListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProblemMetadataListResponse)
	err := c.cc.Invoke(ctx, ProblemsService_GetProblemMetadataList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemsServiceClient) AddTestCases(ctx context.Context, in *AddTestCasesRequest, opts ...grpc.CallOption) (*AddTestCasesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddTestCasesResponse)
	err := c.cc.Invoke(ctx, ProblemsService_AddTestCases_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemsServiceClient) DeleteTestCase(ctx context.Context, in *DeleteTestCaseRequest, opts ...grpc.CallOption) (*DeleteTestCaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTestCaseResponse)
	err := c.cc.Invoke(ctx, ProblemsService_DeleteTestCase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemsServiceClient) GetLanguageSupports(ctx context.Context, in *GetLanguageSupportsRequest, opts ...grpc.CallOption) (*GetLanguageSupportsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLanguageSupportsResponse)
	err := c.cc.Invoke(ctx, ProblemsService_GetLanguageSupports_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemsServiceClient) AddLanguageSupport(ctx context.Context, in *AddLanguageSupportRequest, opts ...grpc.CallOption) (*AddLanguageSupportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddLanguageSupportResponse)
	err := c.cc.Invoke(ctx, ProblemsService_AddLanguageSupport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemsServiceClient) UpdateLanguageSupport(ctx context.Context, in *UpdateLanguageSupportRequest, opts ...grpc.CallOption) (*UpdateLanguageSupportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateLanguageSupportResponse)
	err := c.cc.Invoke(ctx, ProblemsService_UpdateLanguageSupport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemsServiceClient) RemoveLanguageSupport(ctx context.Context, in *RemoveLanguageSupportRequest, opts ...grpc.CallOption) (*RemoveLanguageSupportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveLanguageSupportResponse)
	err := c.cc.Invoke(ctx, ProblemsService_RemoveLanguageSupport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemsServiceClient) FullValidationByProblemId(ctx context.Context, in *FullValidationByProblemIdRequest, opts ...grpc.CallOption) (*FullValidationByProblemIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FullValidationByProblemIdResponse)
	err := c.cc.Invoke(ctx, ProblemsService_FullValidationByProblemId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemsServiceClient) RunUserCodeProblem(ctx context.Context, in *RunProblemRequest, opts ...grpc.CallOption) (*RunProblemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunProblemResponse)
	err := c.cc.Invoke(ctx, ProblemsService_RunUserCodeProblem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemsServiceClient) GetSubmissionsByOptionalProblemId(ctx context.Context, in *GetSubmissionsRequest, opts ...grpc.CallOption) (*GetSubmissionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSubmissionsResponse)
	err := c.cc.Invoke(ctx, ProblemsService_GetSubmissionsByOptionalProblemId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemsServiceClient) GetSubmissionsById(ctx context.Context, in *GetSubmissionsByIdRequest, opts ...grpc.CallOption) (*GetSubmissionsByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSubmissionsByIdResponse)
	err := c.cc.Invoke(ctx, ProblemsService_GetSubmissionsById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemsServiceClient) GetProblemsDoneStatistics(ctx context.Context, in *GetProblemsDoneStatisticsRequest, opts ...grpc.CallOption) (*GetProblemsDoneStatisticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProblemsDoneStatisticsResponse)
	err := c.cc.Invoke(ctx, ProblemsService_GetProblemsDoneStatistics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemsServiceClient) ForceChangeUserEntityInSubmission(ctx context.Context, in *ForceChangeUserEntityInSubmissionRequest, opts ...grpc.CallOption) (*ForceChangeUserEntityInSubmissionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForceChangeUserEntityInSubmissionResponse)
	err := c.cc.Invoke(ctx, ProblemsService_ForceChangeUserEntityInSubmission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemsServiceClient) GetMonthlyActivityHeatmap(ctx context.Context, in *GetMonthlyActivityHeatmapRequest, opts ...grpc.CallOption) (*GetMonthlyActivityHeatmapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMonthlyActivityHeatmapResponse)
	err := c.cc.Invoke(ctx, ProblemsService_GetMonthlyActivityHeatmap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemsServiceClient) GetTopKGlobal(ctx context.Context, in *GetTopKGlobalRequest, opts ...grpc.CallOption) (*GetTopKGlobalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTopKGlobalResponse)
	err := c.cc.Invoke(ctx, ProblemsService_GetTopKGlobal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemsServiceClient) GetTopKEntity(ctx context.Context, in *GetTopKEntityRequest, opts ...grpc.CallOption) (*GetTopKEntityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTopKEntityResponse)
	err := c.cc.Invoke(ctx, ProblemsService_GetTopKEntity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemsServiceClient) GetUserRank(ctx context.Context, in *GetUserRankRequest, opts ...grpc.CallOption) (*GetUserRankResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserRankResponse)
	err := c.cc.Invoke(ctx, ProblemsService_GetUserRank_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemsServiceClient) GetLeaderboardData(ctx context.Context, in *GetLeaderboardDataRequest, opts ...grpc.CallOption) (*GetLeaderboardDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLeaderboardDataResponse)
	err := c.cc.Invoke(ctx, ProblemsService_GetLeaderboardData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemsServiceClient) GetBulkProblemMetadata(ctx context.Context, in *GetBulkProblemMetadataRequest, opts ...grpc.CallOption) (*GetBulkProblemMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBulkProblemMetadataResponse)
	err := c.cc.Invoke(ctx, ProblemsService_GetBulkProblemMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemsServiceClient) VerifyProblemExistenceBulk(ctx context.Context, in *VerifyProblemExistenceBulkRequest, opts ...grpc.CallOption) (*VerifyProblemExistenceBulkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyProblemExistenceBulkResponse)
	err := c.cc.Invoke(ctx, ProblemsService_VerifyProblemExistenceBulk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemsServiceClient) RandomProblemIdsGenWithDifficultyRatio(ctx context.Context, in *RandomProblemIdsGenWithDifficultyRatioRequest, opts ...grpc.CallOption) (*RandomProblemIdsGenWithDifficultyRatioResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RandomProblemIdsGenWithDifficultyRatioResponse)
	err := c.cc.Invoke(ctx, ProblemsService_RandomProblemIdsGenWithDifficultyRatio_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemsServiceClient) ProblemIdsDoneByUserId(ctx context.Context, in *ProblemIdsDoneByUserIdRequest, opts ...grpc.CallOption) (*ProblemIdsDoneByUserIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProblemIdsDoneByUserIdResponse)
	err := c.cc.Invoke(ctx, ProblemsService_ProblemIdsDoneByUserId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *problemsServiceClient) ProblemCountMetadata(ctx context.Context, in *ProblemCountMetadataRequest, opts ...grpc.CallOption) (*ProblemCountMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProblemCountMetadataResponse)
	err := c.cc.Invoke(ctx, ProblemsService_ProblemCountMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProblemsServiceServer is the server API for ProblemsService service.
// All implementations must embed UnimplementedProblemsServiceServer
// for forward compatibility.
type ProblemsServiceServer interface {
	CreateProblem(context.Context, *CreateProblemRequest) (*CreateProblemResponse, error)
	UpdateProblem(context.Context, *UpdateProblemRequest) (*UpdateProblemResponse, error)
	DeleteProblem(context.Context, *DeleteProblemRequest) (*DeleteProblemResponse, error)
	GetProblem(context.Context, *GetProblemRequest) (*GetProblemResponse, error)
	ListProblems(context.Context, *ListProblemsRequest) (*ListProblemsResponse, error)
	GetProblemByIdSlug(context.Context, *GetProblemByIdSlugRequest) (*GetProblemByIdSlugResponse, error)
	GetProblemMetadataList(context.Context, *GetProblemMetadataListRequest) (*GetProblemMetadataListResponse, error)
	AddTestCases(context.Context, *AddTestCasesRequest) (*AddTestCasesResponse, error)
	// rpc EditTestcases(EditTestcasesRequest) returns (EditTestCasesResponse); TODO : use testcaseId for updates :priority low
	DeleteTestCase(context.Context, *DeleteTestCaseRequest) (*DeleteTestCaseResponse, error)
	GetLanguageSupports(context.Context, *GetLanguageSupportsRequest) (*GetLanguageSupportsResponse, error)
	AddLanguageSupport(context.Context, *AddLanguageSupportRequest) (*AddLanguageSupportResponse, error)
	UpdateLanguageSupport(context.Context, *UpdateLanguageSupportRequest) (*UpdateLanguageSupportResponse, error)
	RemoveLanguageSupport(context.Context, *RemoveLanguageSupportRequest) (*RemoveLanguageSupportResponse, error)
	FullValidationByProblemId(context.Context, *FullValidationByProblemIdRequest) (*FullValidationByProblemIdResponse, error)
	RunUserCodeProblem(context.Context, *RunProblemRequest) (*RunProblemResponse, error)
	GetSubmissionsByOptionalProblemId(context.Context, *GetSubmissionsRequest) (*GetSubmissionsResponse, error)
	GetSubmissionsById(context.Context, *GetSubmissionsByIdRequest) (*GetSubmissionsByIdResponse, error)
	// Leaderboard
	GetProblemsDoneStatistics(context.Context, *GetProblemsDoneStatisticsRequest) (*GetProblemsDoneStatisticsResponse, error)
	ForceChangeUserEntityInSubmission(context.Context, *ForceChangeUserEntityInSubmissionRequest) (*ForceChangeUserEntityInSubmissionResponse, error)
	// Activity Contribution
	GetMonthlyActivityHeatmap(context.Context, *GetMonthlyActivityHeatmapRequest) (*GetMonthlyActivityHeatmapResponse, error)
	// Leaderboard Methods
	GetTopKGlobal(context.Context, *GetTopKGlobalRequest) (*GetTopKGlobalResponse, error)
	GetTopKEntity(context.Context, *GetTopKEntityRequest) (*GetTopKEntityResponse, error)
	GetUserRank(context.Context, *GetUserRankRequest) (*GetUserRankResponse, error)
	GetLeaderboardData(context.Context, *GetLeaderboardDataRequest) (*GetLeaderboardDataResponse, error)
	GetBulkProblemMetadata(context.Context, *GetBulkProblemMetadataRequest) (*GetBulkProblemMetadataResponse, error)
	VerifyProblemExistenceBulk(context.Context, *VerifyProblemExistenceBulkRequest) (*VerifyProblemExistenceBulkResponse, error)
	RandomProblemIdsGenWithDifficultyRatio(context.Context, *RandomProblemIdsGenWithDifficultyRatioRequest) (*RandomProblemIdsGenWithDifficultyRatioResponse, error)
	ProblemIdsDoneByUserId(context.Context, *ProblemIdsDoneByUserIdRequest) (*ProblemIdsDoneByUserIdResponse, error)
	ProblemCountMetadata(context.Context, *ProblemCountMetadataRequest) (*ProblemCountMetadataResponse, error)
	mustEmbedUnimplementedProblemsServiceServer()
}

// UnimplementedProblemsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProblemsServiceServer struct{}

func (UnimplementedProblemsServiceServer) CreateProblem(context.Context, *CreateProblemRequest) (*CreateProblemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProblem not implemented")
}
func (UnimplementedProblemsServiceServer) UpdateProblem(context.Context, *UpdateProblemRequest) (*UpdateProblemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProblem not implemented")
}
func (UnimplementedProblemsServiceServer) DeleteProblem(context.Context, *DeleteProblemRequest) (*DeleteProblemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProblem not implemented")
}
func (UnimplementedProblemsServiceServer) GetProblem(context.Context, *GetProblemRequest) (*GetProblemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProblem not implemented")
}
func (UnimplementedProblemsServiceServer) ListProblems(context.Context, *ListProblemsRequest) (*ListProblemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProblems not implemented")
}
func (UnimplementedProblemsServiceServer) GetProblemByIdSlug(context.Context, *GetProblemByIdSlugRequest) (*GetProblemByIdSlugResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProblemByIdSlug not implemented")
}
func (UnimplementedProblemsServiceServer) GetProblemMetadataList(context.Context, *GetProblemMetadataListRequest) (*GetProblemMetadataListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProblemMetadataList not implemented")
}
func (UnimplementedProblemsServiceServer) AddTestCases(context.Context, *AddTestCasesRequest) (*AddTestCasesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTestCases not implemented")
}
func (UnimplementedProblemsServiceServer) DeleteTestCase(context.Context, *DeleteTestCaseRequest) (*DeleteTestCaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTestCase not implemented")
}
func (UnimplementedProblemsServiceServer) GetLanguageSupports(context.Context, *GetLanguageSupportsRequest) (*GetLanguageSupportsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLanguageSupports not implemented")
}
func (UnimplementedProblemsServiceServer) AddLanguageSupport(context.Context, *AddLanguageSupportRequest) (*AddLanguageSupportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddLanguageSupport not implemented")
}
func (UnimplementedProblemsServiceServer) UpdateLanguageSupport(context.Context, *UpdateLanguageSupportRequest) (*UpdateLanguageSupportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLanguageSupport not implemented")
}
func (UnimplementedProblemsServiceServer) RemoveLanguageSupport(context.Context, *RemoveLanguageSupportRequest) (*RemoveLanguageSupportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveLanguageSupport not implemented")
}
func (UnimplementedProblemsServiceServer) FullValidationByProblemId(context.Context, *FullValidationByProblemIdRequest) (*FullValidationByProblemIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FullValidationByProblemId not implemented")
}
func (UnimplementedProblemsServiceServer) RunUserCodeProblem(context.Context, *RunProblemRequest) (*RunProblemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunUserCodeProblem not implemented")
}
func (UnimplementedProblemsServiceServer) GetSubmissionsByOptionalProblemId(context.Context, *GetSubmissionsRequest) (*GetSubmissionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSubmissionsByOptionalProblemId not implemented")
}
func (UnimplementedProblemsServiceServer) GetSubmissionsById(context.Context, *GetSubmissionsByIdRequest) (*GetSubmissionsByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSubmissionsById not implemented")
}
func (UnimplementedProblemsServiceServer) GetProblemsDoneStatistics(context.Context, *GetProblemsDoneStatisticsRequest) (*GetProblemsDoneStatisticsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProblemsDoneStatistics not implemented")
}
func (UnimplementedProblemsServiceServer) ForceChangeUserEntityInSubmission(context.Context, *ForceChangeUserEntityInSubmissionRequest) (*ForceChangeUserEntityInSubmissionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForceChangeUserEntityInSubmission not implemented")
}
func (UnimplementedProblemsServiceServer) GetMonthlyActivityHeatmap(context.Context, *GetMonthlyActivityHeatmapRequest) (*GetMonthlyActivityHeatmapResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMonthlyActivityHeatmap not implemented")
}
func (UnimplementedProblemsServiceServer) GetTopKGlobal(context.Context, *GetTopKGlobalRequest) (*GetTopKGlobalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopKGlobal not implemented")
}
func (UnimplementedProblemsServiceServer) GetTopKEntity(context.Context, *GetTopKEntityRequest) (*GetTopKEntityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopKEntity not implemented")
}
func (UnimplementedProblemsServiceServer) GetUserRank(context.Context, *GetUserRankRequest) (*GetUserRankResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserRank not implemented")
}
func (UnimplementedProblemsServiceServer) GetLeaderboardData(context.Context, *GetLeaderboardDataRequest) (*GetLeaderboardDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLeaderboardData not implemented")
}
func (UnimplementedProblemsServiceServer) GetBulkProblemMetadata(context.Context, *GetBulkProblemMetadataRequest) (*GetBulkProblemMetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBulkProblemMetadata not implemented")
}
func (UnimplementedProblemsServiceServer) VerifyProblemExistenceBulk(context.Context, *VerifyProblemExistenceBulkRequest) (*VerifyProblemExistenceBulkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyProblemExistenceBulk not implemented")
}
func (UnimplementedProblemsServiceServer) RandomProblemIdsGenWithDifficultyRatio(context.Context, *RandomProblemIdsGenWithDifficultyRatioRequest) (*RandomProblemIdsGenWithDifficultyRatioResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RandomProblemIdsGenWithDifficultyRatio not implemented")
}
func (UnimplementedProblemsServiceServer) ProblemIdsDoneByUserId(context.Context, *ProblemIdsDoneByUserIdRequest) (*ProblemIdsDoneByUserIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProblemIdsDoneByUserId not implemented")
}
func (UnimplementedProblemsServiceServer) ProblemCountMetadata(context.Context, *ProblemCountMetadataRequest) (*ProblemCountMetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProblemCountMetadata not implemented")
}
func (UnimplementedProblemsServiceServer) mustEmbedUnimplementedProblemsServiceServer() {}
func (UnimplementedProblemsServiceServer) testEmbeddedByValue()                         {}

// UnsafeProblemsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProblemsServiceServer will
// result in compilation errors.
type UnsafeProblemsServiceServer interface {
	mustEmbedUnimplementedProblemsServiceServer()
}

func RegisterProblemsServiceServer(s grpc.ServiceRegistrar, srv ProblemsServiceServer) {
	// If the following call pancis, it indicates UnimplementedProblemsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProblemsService_ServiceDesc, srv)
}

func _ProblemsService_CreateProblem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProblemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemsServiceServer).CreateProblem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProblemsService_CreateProblem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemsServiceServer).CreateProblem(ctx, req.(*CreateProblemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemsService_UpdateProblem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProblemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemsServiceServer).UpdateProblem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProblemsService_UpdateProblem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemsServiceServer).UpdateProblem(ctx, req.(*UpdateProblemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemsService_DeleteProblem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProblemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemsServiceServer).DeleteProblem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProblemsService_DeleteProblem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemsServiceServer).DeleteProblem(ctx, req.(*DeleteProblemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemsService_GetProblem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProblemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemsServiceServer).GetProblem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProblemsService_GetProblem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemsServiceServer).GetProblem(ctx, req.(*GetProblemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemsService_ListProblems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProblemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemsServiceServer).ListProblems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProblemsService_ListProblems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemsServiceServer).ListProblems(ctx, req.(*ListProblemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemsService_GetProblemByIdSlug_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProblemByIdSlugRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemsServiceServer).GetProblemByIdSlug(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProblemsService_GetProblemByIdSlug_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemsServiceServer).GetProblemByIdSlug(ctx, req.(*GetProblemByIdSlugRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemsService_GetProblemMetadataList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProblemMetadataListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemsServiceServer).GetProblemMetadataList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProblemsService_GetProblemMetadataList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemsServiceServer).GetProblemMetadataList(ctx, req.(*GetProblemMetadataListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemsService_AddTestCases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTestCasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemsServiceServer).AddTestCases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProblemsService_AddTestCases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemsServiceServer).AddTestCases(ctx, req.(*AddTestCasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemsService_DeleteTestCase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTestCaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemsServiceServer).DeleteTestCase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProblemsService_DeleteTestCase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemsServiceServer).DeleteTestCase(ctx, req.(*DeleteTestCaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemsService_GetLanguageSupports_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLanguageSupportsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemsServiceServer).GetLanguageSupports(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProblemsService_GetLanguageSupports_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemsServiceServer).GetLanguageSupports(ctx, req.(*GetLanguageSupportsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemsService_AddLanguageSupport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddLanguageSupportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemsServiceServer).AddLanguageSupport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProblemsService_AddLanguageSupport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemsServiceServer).AddLanguageSupport(ctx, req.(*AddLanguageSupportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemsService_UpdateLanguageSupport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLanguageSupportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemsServiceServer).UpdateLanguageSupport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProblemsService_UpdateLanguageSupport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemsServiceServer).UpdateLanguageSupport(ctx, req.(*UpdateLanguageSupportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemsService_RemoveLanguageSupport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveLanguageSupportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemsServiceServer).RemoveLanguageSupport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProblemsService_RemoveLanguageSupport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemsServiceServer).RemoveLanguageSupport(ctx, req.(*RemoveLanguageSupportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemsService_FullValidationByProblemId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FullValidationByProblemIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemsServiceServer).FullValidationByProblemId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProblemsService_FullValidationByProblemId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemsServiceServer).FullValidationByProblemId(ctx, req.(*FullValidationByProblemIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemsService_RunUserCodeProblem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunProblemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemsServiceServer).RunUserCodeProblem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProblemsService_RunUserCodeProblem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemsServiceServer).RunUserCodeProblem(ctx, req.(*RunProblemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemsService_GetSubmissionsByOptionalProblemId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubmissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemsServiceServer).GetSubmissionsByOptionalProblemId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProblemsService_GetSubmissionsByOptionalProblemId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemsServiceServer).GetSubmissionsByOptionalProblemId(ctx, req.(*GetSubmissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemsService_GetSubmissionsById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubmissionsByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemsServiceServer).GetSubmissionsById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProblemsService_GetSubmissionsById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemsServiceServer).GetSubmissionsById(ctx, req.(*GetSubmissionsByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemsService_GetProblemsDoneStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProblemsDoneStatisticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemsServiceServer).GetProblemsDoneStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProblemsService_GetProblemsDoneStatistics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemsServiceServer).GetProblemsDoneStatistics(ctx, req.(*GetProblemsDoneStatisticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemsService_ForceChangeUserEntityInSubmission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForceChangeUserEntityInSubmissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemsServiceServer).ForceChangeUserEntityInSubmission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProblemsService_ForceChangeUserEntityInSubmission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemsServiceServer).ForceChangeUserEntityInSubmission(ctx, req.(*ForceChangeUserEntityInSubmissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemsService_GetMonthlyActivityHeatmap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMonthlyActivityHeatmapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemsServiceServer).GetMonthlyActivityHeatmap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProblemsService_GetMonthlyActivityHeatmap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemsServiceServer).GetMonthlyActivityHeatmap(ctx, req.(*GetMonthlyActivityHeatmapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemsService_GetTopKGlobal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopKGlobalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemsServiceServer).GetTopKGlobal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProblemsService_GetTopKGlobal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemsServiceServer).GetTopKGlobal(ctx, req.(*GetTopKGlobalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemsService_GetTopKEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopKEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemsServiceServer).GetTopKEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProblemsService_GetTopKEntity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemsServiceServer).GetTopKEntity(ctx, req.(*GetTopKEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemsService_GetUserRank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRankRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemsServiceServer).GetUserRank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProblemsService_GetUserRank_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemsServiceServer).GetUserRank(ctx, req.(*GetUserRankRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemsService_GetLeaderboardData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLeaderboardDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemsServiceServer).GetLeaderboardData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProblemsService_GetLeaderboardData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemsServiceServer).GetLeaderboardData(ctx, req.(*GetLeaderboardDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemsService_GetBulkProblemMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBulkProblemMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemsServiceServer).GetBulkProblemMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProblemsService_GetBulkProblemMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemsServiceServer).GetBulkProblemMetadata(ctx, req.(*GetBulkProblemMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemsService_VerifyProblemExistenceBulk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyProblemExistenceBulkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemsServiceServer).VerifyProblemExistenceBulk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProblemsService_VerifyProblemExistenceBulk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemsServiceServer).VerifyProblemExistenceBulk(ctx, req.(*VerifyProblemExistenceBulkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemsService_RandomProblemIdsGenWithDifficultyRatio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RandomProblemIdsGenWithDifficultyRatioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemsServiceServer).RandomProblemIdsGenWithDifficultyRatio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProblemsService_RandomProblemIdsGenWithDifficultyRatio_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemsServiceServer).RandomProblemIdsGenWithDifficultyRatio(ctx, req.(*RandomProblemIdsGenWithDifficultyRatioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemsService_ProblemIdsDoneByUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProblemIdsDoneByUserIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemsServiceServer).ProblemIdsDoneByUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProblemsService_ProblemIdsDoneByUserId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemsServiceServer).ProblemIdsDoneByUserId(ctx, req.(*ProblemIdsDoneByUserIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProblemsService_ProblemCountMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProblemCountMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProblemsServiceServer).ProblemCountMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProblemsService_ProblemCountMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProblemsServiceServer).ProblemCountMetadata(ctx, req.(*ProblemCountMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProblemsService_ServiceDesc is the grpc.ServiceDesc for ProblemsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProblemsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "problems.ProblemsService",
	HandlerType: (*ProblemsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProblem",
			Handler:    _ProblemsService_CreateProblem_Handler,
		},
		{
			MethodName: "UpdateProblem",
			Handler:    _ProblemsService_UpdateProblem_Handler,
		},
		{
			MethodName: "DeleteProblem",
			Handler:    _ProblemsService_DeleteProblem_Handler,
		},
		{
			MethodName: "GetProblem",
			Handler:    _ProblemsService_GetProblem_Handler,
		},
		{
			MethodName: "ListProblems",
			Handler:    _ProblemsService_ListProblems_Handler,
		},
		{
			MethodName: "GetProblemByIdSlug",
			Handler:    _ProblemsService_GetProblemByIdSlug_Handler,
		},
		{
			MethodName: "GetProblemMetadataList",
			Handler:    _ProblemsService_GetProblemMetadataList_Handler,
		},
		{
			MethodName: "AddTestCases",
			Handler:    _ProblemsService_AddTestCases_Handler,
		},
		{
			MethodName: "DeleteTestCase",
			Handler:    _ProblemsService_DeleteTestCase_Handler,
		},
		{
			MethodName: "GetLanguageSupports",
			Handler:    _ProblemsService_GetLanguageSupports_Handler,
		},
		{
			MethodName: "AddLanguageSupport",
			Handler:    _ProblemsService_AddLanguageSupport_Handler,
		},
		{
			MethodName: "UpdateLanguageSupport",
			Handler:    _ProblemsService_UpdateLanguageSupport_Handler,
		},
		{
			MethodName: "RemoveLanguageSupport",
			Handler:    _ProblemsService_RemoveLanguageSupport_Handler,
		},
		{
			MethodName: "FullValidationByProblemId",
			Handler:    _ProblemsService_FullValidationByProblemId_Handler,
		},
		{
			MethodName: "RunUserCodeProblem",
			Handler:    _ProblemsService_RunUserCodeProblem_Handler,
		},
		{
			MethodName: "GetSubmissionsByOptionalProblemId",
			Handler:    _ProblemsService_GetSubmissionsByOptionalProblemId_Handler,
		},
		{
			MethodName: "GetSubmissionsById",
			Handler:    _ProblemsService_GetSubmissionsById_Handler,
		},
		{
			MethodName: "GetProblemsDoneStatistics",
			Handler:    _ProblemsService_GetProblemsDoneStatistics_Handler,
		},
		{
			MethodName: "ForceChangeUserEntityInSubmission",
			Handler:    _ProblemsService_ForceChangeUserEntityInSubmission_Handler,
		},
		{
			MethodName: "GetMonthlyActivityHeatmap",
			Handler:    _ProblemsService_GetMonthlyActivityHeatmap_Handler,
		},
		{
			MethodName: "GetTopKGlobal",
			Handler:    _ProblemsService_GetTopKGlobal_Handler,
		},
		{
			MethodName: "GetTopKEntity",
			Handler:    _ProblemsService_GetTopKEntity_Handler,
		},
		{
			MethodName: "GetUserRank",
			Handler:    _ProblemsService_GetUserRank_Handler,
		},
		{
			MethodName: "GetLeaderboardData",
			Handler:    _ProblemsService_GetLeaderboardData_Handler,
		},
		{
			MethodName: "GetBulkProblemMetadata",
			Handler:    _ProblemsService_GetBulkProblemMetadata_Handler,
		},
		{
			MethodName: "VerifyProblemExistenceBulk",
			Handler:    _ProblemsService_VerifyProblemExistenceBulk_Handler,
		},
		{
			MethodName: "RandomProblemIdsGenWithDifficultyRatio",
			Handler:    _ProblemsService_RandomProblemIdsGenWithDifficultyRatio_Handler,
		},
		{
			MethodName: "ProblemIdsDoneByUserId",
			Handler:    _ProblemsService_ProblemIdsDoneByUserId_Handler,
		},
		{
			MethodName: "ProblemCountMetadata",
			Handler:    _ProblemsService_ProblemCountMetadata_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ProblemsService/problemsservice.proto",
}
